### ISSUE TITLE
想请问一下

### ISSUE THREAD

**Issue by jzh3468** [steven010116/epic7autoBookmark#1]
按照设置，检测的时候能检测出金币，天空石检测不出来，没法启动是怎么回事啊，钻石是5位数

**Comment by steven010116** [comment]
兄弟你用bluestack左側的截屏工具截個圖放上來我測試看看

**Comment by jzh3468** [comment]
好怪，今天可以了又。感谢老哥了

**Comment by jzh3468** [comment]
> 

好像是数字问题，有时候就不行，手动刷几次就检测正常了

**Comment by steven010116** [comment]
這個問題比較沒法解決，tesseract比較傳統的光學文字辨識，主要是懶，不想手動填數字啥的，下次BS改版跟著更新會考慮做成手動輸入的。

**Comment by steven010116** [comment]
我把OCR的文字辨識拿掉了，會停住主要都是辨識不到，改成手填的會比較正常些。

**Comment by jzh3468** [comment]
> 我把OCR的文字辨識拿掉了，會停住主要都是辨識不到，改成手填的會比較正常些。

太感谢了！
