### ISSUE TITLE
国服问题

### ISSUE THREAD

**Issue by OchiaiNao** [steven010116/epic7autoBookmark#2]
神秘商店的购买页面更改成这样了，请问在原先的判断基础上是否只需要更改Y-axis的值即可？
![img](https://github.com/steven010116/epic7autoBookmark/assets/112594689/e605d31e-dbeb-44ed-974d-6217aeaa310b)

P.S. 第一次研究pyinstaller， 对spec进行build后好像生成的exe并不能打开，请问该如何解决（）

**Comment by Wrong-pixel** [comment]
> 神秘商店的购买页面更改成这样了，请问在原先的判断基础上是否只需要更改Y-axis的值即可？ ![img](https://user-images.githubusercontent.com/112594689/247388653-e605d31e-dbeb-44ed-974d-6217aeaa310b.png)
> 
> P.S. 第一次研究pyinstaller， 对spec进行build后好像生成的exe并不能打开，请问该如何解决（）

在大佬的基础上魔改了国服版工具，可以参考https://github.com/Wrong-pixel/epic7auto
